import {useMediaQuery} from "@mantine/hooks";
import Head from "next/head";
import {Anchor, Box, Button, Flex, Text} from "@mantine/core";
import styles from "./index.module.scss";
import Image from "next/image";
import IconCheck from "../../../public/images/icon-checkmark.svg";
import IconPhone from "../../../public/images/icon-phone.svg";
import IconClipboard from "../../../public/images/icon-clipboard.svg";
import {Carousel} from "@mantine/carousel";
import ArrowRight from "../../../public/images/carousel-arrow-right.svg";
import ArrowLeft from "../../../public/images/carousel-arrow.svg";
import IconCalculator from "../../../public/images/icon-calculator.svg";
import IconDebtSettlement from "../../../public/images/icon-debt-settlement.svg";
import IconPiggybank from "../../../public/images/icon-piggybank.svg";
import IconCash from "../../../public/images/icon-cash.svg";
import cl from "classnames";
export default function Home() {
    const matches = useMediaQuery('(max-width: 834px)');
    return (
        <>
            <Head>
                <title>Main</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
                <meta name='keywords' content='test keywords, test2 rew rew,rewrwe'/>
            </Head>
            <Box className={'container'}>
                <Box mt={matches ? 24 : 50}>
                    {/*<MainCarousel />*/}
                </Box>
                <Box className={styles.sectionTwo}>
                    <div className={styles.boxLeft}>
                        <Text component={'p'} className={styles.title}>
                            mainSectionTwoTitle
                        </Text>
                        <Flex className={styles.textWrapper} columnGap={12} align={'center'}>
                            <Image
                                priority
                                src={IconCheck}
                                alt="Follow us on Twitter"
                            />
                            <Text className={styles.text}>
                                sectionTwoTextOne
                            </Text>
                        </Flex>
                        <Flex className={styles.textWrapper} columnGap={12} align={'center'}>
                            <Image
                                priority
                                src={IconCheck}
                                alt="Follow us on Twitter"
                            />
                            <Text className={styles.text}>
                                sectionTwoTextTwo
                            </Text>
                        </Flex>
                        <Flex className={styles.textWrapper} columnGap={12} align={'center'}>
                            <Image
                                priority
                                src={IconCheck}
                                alt="Follow us on Twitter"
                            />
                            <Text className={styles.text}>
                                sectionTwoTextThree
                            </Text>
                        </Flex>
                        <Flex className={styles.textWrapper} columnGap={12} align={'center'}>
                            <Image
                                priority
                                src={IconCheck}
                                alt="Follow us on Twitter"
                            />
                            <Text className={styles.text}>
                                sectionTwoTextFour
                            </Text>
                        </Flex>
                        <Flex className={styles.textWrapper} columnGap={12} align={'center'}>
                            <Image
                                priority
                                src={IconCheck}
                                alt="Follow us on Twitter"
                            />
                            <Text className={styles.text}>
                                sectionTwoTextFive
                            </Text>
                        </Flex>
                    </div>
                    <div className={styles.boxRight}>
                        <Text component={'p'} className={'title'}>
                            contact
                        </Text>

                        <Flex m={'24px 0 16px'} align={'center'} columnGap={11}>
                            <Image
                                priority
                                src={IconPhone}
                                alt="Follow us on Twitter"
                            />
                            <Anchor className={styles.phoneNumber} href={'tel:+998712023434'}>
                                +998 71 202 34 34
                            </Anchor>
                        </Flex>
                        <Text component={'p'} className={styles.text}>
                            {/*<Trans components={{ b: <span /> }}>*/}
                            {/*    sectionTwoContactText*/}
                            {/*</Trans>*/}
                        </Text>
                        <Button className={styles.btn} leftIcon={ <Image
                            priority
                            src={IconClipboard}
                            alt="Follow us on Twitter"
                        />}>
                            submitApplication
                        </Button>
                    </div>
                </Box>
                <Box mt={matches ? 40 : 80}>
                    {/*<Statistics />*/}
                </Box>
                <div className={styles.sectionFour}>
                    <div className={styles.textWrapper}>
                        <Text component={'p'} className={'title'}>
                            {/*<Trans components={{ br: <br /> }}>*/}
                            {/*    activities*/}
                            {/*</Trans>*/}
                        </Text>
                    </div>
                    {matches && <Carousel
                        w={'100%'}
                        height={150}
                        slideSize={300}
                        slideGap={16}
                        loop
                        align='center'
                        slidesToScroll={1}
                        className={styles.carousel}
                        nextControlIcon={ <Image
                            priority
                            src={ArrowRight}
                            alt="Follow us on Twitter"
                        />}
                        previousControlIcon={ <Image
                            priority
                            src={ArrowLeft}
                            alt="Follow us on Twitter"
                        />}
                    >
                        <Carousel.Slide>
                            <div onClick={() => {
                                // navigate(`/${routePaths.monitoringLevelOverdue}`);
                                scrollTo({
                                    top: 0,
                                })
                            }} className={styles.card}>
                                <Flex columnGap={12}>
                                    <div className={styles.icon}>
                                        <Image
                                            priority
                                            src={IconCalculator}
                                            alt="Follow us on Twitter"
                                        />
                                    </div>
                                    <Text component={'p'} className={styles.cardTitle}>
                                        {/*<Trans components={{ span: <p /> }}>*/}
                                        {/*    activitiesMainOne*/}
                                        {/*</Trans>*/}
                                        test
                                    </Text>
                                </Flex>
                            </div>
                        </Carousel.Slide>
                        <Carousel.Slide>
                            <div onClick={() => {
                                // navigate(`/${routePaths.debtSettlement}`);
                                scrollTo({top: 0})
                            }} className={styles.card}>
                                <Flex columnGap={12}>
                                    <div className={styles.icon}>
                                        <Image
                                            priority
                                            src={IconDebtSettlement}
                                            alt="Follow us on Twitter"
                                        />
                                    </div>
                                    <Text component={'p'} className={styles.cardTitle}>
                                        {/*<Trans components={{ span: <p />, br: <span /> }}>*/}
                                        {/*    activitiesTwo*/}
                                        {/*</Trans>*/}
                                    </Text>
                                </Flex>
                            </div>
                        </Carousel.Slide>
                        <Carousel.Slide>
                            <div onClick={() => {
                                // navigate(`/${routePaths.portfolioAnalysis}`);
                                scrollTo({top: 0})
                            }} className={styles.card}>
                                <Flex columnGap={12}>
                                    <div className={styles.icon}>
                                        <Image
                                            priority
                                            src={IconPiggybank}
                                            alt="Follow us on Twitter"
                                        />
                                    </div>
                                    <Text component={'p'} className={styles.cardTitle}>
                                        {/*<Trans components={{span: <p/>, br: <span/>}}>*/}
                                        {/*    activitiesThree*/}
                                        {/*</Trans>*/}
                                    </Text>
                                </Flex>
                            </div>
                        </Carousel.Slide>
                        <Carousel.Slide>
                            <div onClick={() => {
                                // navigate(`/${routePaths.legalSupportRecoveryProcess}`);
                                scrollTo({top: 0})
                            }} className={styles.card}>
                                <Flex columnGap={12}>
                                    <div className={styles.icon}>
                                        <Image
                                            priority
                                            src={IconCash}
                                            alt="Follow us on Twitter"
                                        />
                                    </div>
                                    <Text component={'p'} className={styles.cardTitle}>
                                        {/*<Trans components={{ span: <p />, br: <span /> }}>*/}
                                        {/*    activitiesFour*/}
                                        {/*</Trans>*/}
                                    </Text>
                                </Flex>
                            </div>
                        </Carousel.Slide>
                    </Carousel>}

                    <div className={styles.cardsWrapper}>
                        <div onClick={() => {
                            // navigate(`/${routePaths.monitoringLevelOverdue}`);
                            scrollTo({top: 0})
                        }} className={styles.card}>
                            <Flex columnGap={12}>
                                <div className={styles.icon}>
                                    <Image
                                        priority
                                        src={IconCalculator}
                                        alt="Follow us on Twitter"
                                    />
                                </div>
                                <Text component={'p'} className={styles.cardTitle}>
                                    activitiesMainOne
                                </Text>
                            </Flex>
                        </div>
                        <div onClick={() => {
                            // navigate(`/${routePaths.debtSettlement}`);
                            scrollTo({top: 0})
                        }} className={styles.card}>
                            <Flex columnGap={12}>
                                <div className={styles.icon}>
                                    <Image
                                        priority
                                        src={IconDebtSettlement}
                                        alt="Follow us on Twitter"
                                    />
                                </div>
                                <Text component={'p'} className={styles.cardTitle}>
                                    {/*<Trans components={{ span: <p />, br: <span /> }}>*/}
                                    {/*    activitiesTwo*/}
                                    {/*</Trans>*/}
                                </Text>
                            </Flex>
                        </div>
                        <div onClick={() => {
                            // navigate(`/${routePaths.portfolioAnalysis}`);
                            scrollTo({top: 0})
                        }} className={styles.card}>
                            <Flex columnGap={12}>
                                <div className={styles.icon}>
                                    <Image
                                        priority
                                        src={IconPiggybank}
                                        alt="Follow us on Twitter"
                                    />
                                </div>
                                <Text component={'p'} className={styles.cardTitle}>
                                    {/*<Trans components={{ span: <p />, br: <span /> }}>*/}
                                    {/*    activitiesThree*/}
                                    {/*</Trans>*/}
                                </Text>
                            </Flex>
                        </div>
                        <div onClick={() => {
                            // navigate(`/${routePaths.legalSupportRecoveryProcess}`);
                            scrollTo({top: 0})
                        }} className={styles.card}>
                            <Flex columnGap={12}>
                                <div className={styles.icon}>
                                    <Image
                                        priority
                                        src={IconCash}
                                        alt="Follow us on Twitter"
                                    />
                                </div>
                                <Text component={'p'} className={styles.cardTitle}>
                                    {/*<Trans components={{ span: <p />, br: <span /> }}>*/}
                                    {/*    activitiesFour*/}
                                    {/*</Trans>*/}
                                </Text>
                            </Flex>
                        </div>
                    </div>

                </div>
            </Box>
            <div className={cl(styles.sectionFive, 'container')}>
                <Text component={'p'} className={styles.title}>
                    cooperatingReceive
                </Text>
                {!matches && (
                    <>
                        <div className={styles.cards}>
                            {/*{benefitsList?.map((i,index) =>*/}
                            <div className={styles.card}>
                                {/*<CardRectengle className={styles.cardCorner} />*/}
                                {/*<div className={styles.icon}>*/}
                                {/*    <img src={i.icon} alt={'icon'}/>*/}
                                {/*</div>*/}
                                {/*<Text component={'p'}>*/}
                                {/*    { '-' }*/}
                                {/*</Text>*/}
                            </div>
                            {/*)}*/}
                        </div>
                    </>
                )}
                {matches && (
                    <>
                        <ul>
                            {/*{benefitsList?.map((i,index) => <li key={index} >{i?.title}</li> )}*/}
                        </ul>
                    </>
                )}
            </div>
            <Box className={'container'}>
                {/*<News />*/}
            </Box>
        </>
    );
}