export {default as MainCarousel} from "./main-carousel"
export {default as Statistics} from "./statistics"
export {default as WeTrusted} from "./we-trusted"
export {default as News} from "./news"
export {default as OurValues} from "./our-values"
export {default as OurMission} from "./our-mission"
export {default as OtherActivities} from "./other-activities"