export enum routePaths {
  root = '/',
  about = 'about',
  ourServices = 'our-services',
  career = 'career',
  contact = 'contact',
  ourTeam = 'our-team',
  allNews = 'all-news',
  news = 'news/:id',
  monitoringLevelOverdue = 'monitoring-the-level-of-overdue-debts',
  legalSupportRecoveryProcess = 'legal-support-of-the-recovery-process',
  debtSettlement = 'pre-trial-debt-settlement',
  portfolioAnalysis = 'npl-portfolio-analysis',
  notFound = '*',
}
